CREATE USER &&USERNAME IDENTIFIED BY &&PASSWORD;

--ALTER USER &&USERNAME PROFILE &&PROFILE;

GRANT UNLIMITED TABLESPACE TO &&USERNAME;
GRANT CREATE TRIGGER TO &&USERNAME;
GRANT CREATE SEQUENCE TO &&USERNAME;
GRANT CREATE TYPE TO &&USERNAME;
GRANT CREATE PROCEDURE TO &&USERNAME;
GRANT CREATE TABLE TO &&USERNAME;
GRANT DEBUG CONNECT SESSION TO &&USERNAME;
GRANT DEBUG ANY PROCEDURE TO &&USERNAME;
GRANT CREATE DATABASE LINK TO &&USERNAME;
GRANT CREATE VIEW TO &&USERNAME;

GRANT CONNECT TO &&USERNAME;
GRANT PLUSTRACE TO &&USERNAME;