CREATE TABLE M2M_VERSIONS
(
  TECHNICAL_KEY NUMBER,
  PREV_VERSION VARCHAR2(7) NOT NULL,
  THIS_VERSION VARCHAR2(7) NOT NULL,
  VERSION_CHANGE_DATE DATE DEFAULT SYSDATE NOT NULL
);
ALTER TABLE M2M_VERSIONS ADD (
  PRIMARY KEY
 (TECHNICAL_KEY));
CREATE SEQUENCE M2M_VERSION_ID_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 1
  NOORDER;