CREATE TABLE M2M_VERSIONS
(
  TECHNICAL_KEY NUMBER,
  PREV_VERSION VARCHAR2(7) NOT NULL,
  THIS_VERSION VARCHAR2(7) NOT NULL,
  VERSION_CHANGE_DATE DATE DEFAULT SYSDATE NOT NULL
);
ALTER TABLE M2M_VERSIONS ADD 
(
  PRIMARY KEY (TECHNICAL_KEY)
);

CREATE SEQUENCE M2M_VERSION_ID_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
CREATE TABLE M2M_REVINFO 
(
  REV_NO NUMBER(10,0) NOT NULL, 
  REV_TIMESTAMP TIMESTAMP (6), 
  USERNAME VARCHAR2(255 CHAR)
);

ALTER TABLE M2M_REVINFO ADD 
(
  PRIMARY KEY (REV_NO)
);

CREATE TABLE M2M_REVCHANGES 
(
  REV_NO NUMBER(10,0) NOT NULL, 
  ENTITY_NAME VARCHAR2(255 CHAR) 
);
ALTER TABLE M2M_REVCHANGES ADD CONSTRAINT FK_REV_INFO_REV_NO FOREIGN KEY (REV_NO) 
  REFERENCES M2M_REVINFO (REV_NO);


CREATE TABLE M2M_APP_CONFIG 
(
  DESCRIPTION VARCHAR2(100 CHAR) NOT NULL, 
  PARAM_NAME VARCHAR2(100 CHAR) NOT NULL, 
  PARAM_VALUE VARCHAR2(100 CHAR) NOT NULL,
  TECHNICAL_KEY VARCHAR2(36 CHAR) NOT NULL, 
  CREATED_DATE TIMESTAMP (6) NOT NULL, 
  CREATED_BY VARCHAR2(15 CHAR) NOT NULL, 
  INTEGRATION_ID VARCHAR2(100 CHAR) NOT NULL, 
  LAST_MODIFIED_DATE TIMESTAMP NOT NULL, 
  LAST_MODIFIED_BY VARCHAR2(15 CHAR) NOT NULL, 
  MODIFICATION_NO NUMBER(10,0) NOT NULL
);
ALTER TABLE M2M_APP_CONFIG ADD 
(
  PRIMARY KEY (TECHNICAL_KEY)
);


CREATE TABLE M2M_LOV_TYPE 
(
  DESCRIPTION VARCHAR2(100 CHAR), 
  LOV_NAME VARCHAR2(30 CHAR) NOT NULL, 
  PARENT_LOV_TECH_KEY VARCHAR2(36 CHAR),
  TECHNICAL_KEY VARCHAR2(36 CHAR) NOT NULL, 
  CREATED_DATE TIMESTAMP (6) NOT NULL, 
  CREATED_BY VARCHAR2(15 CHAR) NOT NULL, 
  INTEGRATION_ID VARCHAR2(100 CHAR) NOT NULL, 
  LAST_MODIFIED_DATE TIMESTAMP (6) NOT NULL, 
  LAST_MODIFIED_BY VARCHAR2(15 CHAR) NOT NULL, 
  MODIFICATION_NO NUMBER(10,0) NOT NULL
);
ALTER TABLE M2M_LOV_TYPE ADD 
(
  PRIMARY KEY (TECHNICAL_KEY)
);
ALTER TABLE M2M_LOV_TYPE ADD CONSTRAINT FK_LOV_TYPE_PARENT_LOV FOREIGN KEY (PARENT_LOV_TECH_KEY) 
  REFERENCES M2M_LOV_TYPE (TECHNICAL_KEY);


CREATE TABLE M2M_LOV_VALUE 
(
  LIC VARCHAR2(40 CHAR) NOT NULL, 
  STATUS VARCHAR2(255 CHAR),
  LOV_DISC VARCHAR2(31 CHAR) NOT NULL, 
  FROZEN CHAR(1 CHAR), 
  LOV_TYPE_TECH_KEY VARCHAR2(36 CHAR), 
  PARENT_LIC_TECH_KEY VARCHAR2(36 CHAR),
  TECHNICAL_KEY VARCHAR2(36 CHAR) NOT NULL, 
  CREATED_DATE TIMESTAMP (6) NOT NULL, 
  CREATED_BY VARCHAR2(15 CHAR) NOT NULL, 
  INTEGRATION_ID VARCHAR2(100 CHAR) NOT NULL, 
  LAST_MODIFIED_DATE TIMESTAMP (6) NOT NULL, 
  LAST_MODIFIED_BY VARCHAR2(15 CHAR) NOT NULL, 
  MODIFICATION_NO NUMBER(10,0) NOT NULL
);
ALTER TABLE M2M_LOV_VALUE ADD 
(
  PRIMARY KEY (TECHNICAL_KEY)
);
ALTER TABLE M2M_LOV_VALUE ADD CONSTRAINT FK_LOV_TYPE_TECH_KEY FOREIGN KEY (LOV_TYPE_TECH_KEY) 
  REFERENCES M2M_LOV_TYPE (TECHNICAL_KEY);
ALTER TABLE M2M_LOV_VALUE ADD CONSTRAINT FK_LOV_VALUE_PARENT FOREIGN KEY (PARENT_LIC_TECH_KEY) 
  REFERENCES M2M_LOV_VALUE (TECHNICAL_KEY);
ALTER TABLE M2M_LOV_VALUE ADD CONSTRAINT UNQ_LOV_VALUE_LIC UNIQUE (LIC);


CREATE TABLE M2M_LOV_DISPLAY_VALUE 
(
  DISPLAY_VALUE VARCHAR2(40 CHAR) NOT NULL, 
  LANGUAGE VARCHAR2(255 CHAR) NOT NULL, 
  LIC_TECH_KEY VARCHAR2(36 CHAR),
  TECHNICAL_KEY VARCHAR2(36 CHAR) NOT NULL, 
  CREATED_DATE TIMESTAMP (6) NOT NULL, 
  CREATED_BY VARCHAR2(15 CHAR) NOT NULL, 
  INTEGRATION_ID VARCHAR2(100 CHAR) NOT NULL, 
  LAST_MODIFIED_DATE TIMESTAMP (6) NOT NULL, 
  LAST_MODIFIED_BY VARCHAR2(15 CHAR) NOT NULL, 
  MODIFICATION_NO NUMBER(10,0) NOT NULL
);
ALTER TABLE M2M_LOV_DISPLAY_VALUE ADD 
(
  PRIMARY KEY (TECHNICAL_KEY)
);
ALTER TABLE M2M_LOV_DISPLAY_VALUE ADD CONSTRAINT FK_LOV_VALUE_TECH_KEY FOREIGN KEY (LIC_TECH_KEY) 
  REFERENCES M2M_LOV_VALUE (TECHNICAL_KEY);


CREATE TABLE M2M_USER 
(
  USERNAME VARCHAR2(50 CHAR) NOT NULL, 
  PASSWORD VARCHAR2(50 CHAR), 
  USER_TYPE VARCHAR2(36 CHAR) NOT NULL,
  TECHNICAL_KEY VARCHAR2(36 CHAR) NOT NULL, 
  CREATED_DATE TIMESTAMP (6) NOT NULL, 
  CREATED_BY VARCHAR2(15 CHAR) NOT NULL, 
  INTEGRATION_ID VARCHAR2(100 CHAR) NOT NULL, 
  LAST_MODIFIED_DATE TIMESTAMP (6) NOT NULL, 
  LAST_MODIFIED_BY VARCHAR2(15 CHAR) NOT NULL, 
  MODIFICATION_NO NUMBER(10,0) NOT NULL 
);
ALTER TABLE M2M_USER ADD 
(
  PRIMARY KEY (TECHNICAL_KEY)
);
ALTER TABLE M2M_USER ADD CONSTRAINT FK_USER_TYPE_LOV FOREIGN KEY (USER_TYPE) 
  REFERENCES M2M_LOV_VALUE (TECHNICAL_KEY);


CREATE TABLE M2M_USER_AUD 
(
  TECHNICAL_KEY VARCHAR2(36 CHAR) NOT NULL, 
  REV NUMBER(10,0) NOT NULL,
  USERNAME VARCHAR2(50 CHAR),
  PASSWORD VARCHAR2(50 CHAR), 
  USER_TYPE VARCHAR2(36 CHAR),
  REVTYPE NUMBER(3,0), 
  REVEND NUMBER(10,0), 
  REVEND_TSTMP TIMESTAMP (6)
);
ALTER TABLE M2M_USER_AUD ADD 
(
  PRIMARY KEY (TECHNICAL_KEY, REV)
);
ALTER TABLE M2M_USER_AUD ADD CONSTRAINT FK_USER_REVISION_BEGIN FOREIGN KEY (REV) 
  REFERENCES M2M_REVINFO (REV_NO);
ALTER TABLE M2M_USER_AUD ADD CONSTRAINT FK_USER_REVISION_END FOREIGN KEY (REVEND) 
  REFERENCES M2M_REVINFO (REV_NO);
